name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Log in to Docker Hub
      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build Docker image
      - name: Build Docker image
        run: |
          docker build -t sandeepbikkana87/my-app:latest .

      # 4. Run tests inside container
      - name: Run tests
        run: |
          docker run --rm sandeepbikkana87/my-app:latest sh -c "pytest"  # Adjust to your test command

      # 5. Push image to Docker Hub
      - name: Push to Docker Hub
        run: |
          docker push sandeepbikkana87/my-app:latest

